In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Владельцам сайта для продажи билетов в кино нужна помощь.  
В датасете предложен некоторый набор метрик, но он не полный.  
Определите метрики, которые больше всего влияют на доход.  
Для этого постройте пирамиду метрик и проведите корреляционный анализ.

In [4]:
df = pd.read_excel('hw.xlsx')                
df.head()

,Дата,Пользователи,Новые пользователи,Доля новых пользователей,Количество платящих пользователей,Количество платящих пользователей.1,Количество покупок,Количество покупок.1,Количество покупок на платящего пользователя,"Выручка, RUB","Средняя выручка на пользователя, RUB","Средняя выручка на платящего пользователя, RUB",Вернувшиеся,"Выручка, RUB.1","CR воронки покупок, %",Ошибки,CSI
0,2017-12-31,23095,1603,0.069409,1828,0.009687,2309,0.005166,1.263129,0.006339,137.544230,1737.737418,21492,3.176584e+06,19,18854,82
1,2017-12-30,29918,2116,0.070727,2727,0.014452,3413,0.007637,1.251558,0.007972,133.536032,1465.027869,27802,3.995131e+06,19,17506,88
2,2017-12-29,38953,3029,0.077760,4219,0.022358,5142,0.011505,1.218772,0.013854,178.231792,1645.570751,35924,6.942663e+06,18,10910,88
3,2017-12-28,41326,3228,0.078111,4710,0.024960,5732,0.012826,1.216985,0.015377,186.466825,1636.078131,38098,7.705928e+06,17,17235,85
4,2017-12-27,34148,2199,0.064396,3018,0.015994,3713,0.008308,1.230285,0.009173,134.607649,1523.055666,31949,4.596582e+06,13,14190,88

In [5]:
df.dtypes

Дата                                              datetime64[ns]
Пользователи                                               int64
Новые пользователи                                         int64
Доля новых пользователей                                 float64
Количество платящих пользователей                          int64
Количество платящих пользователей.1                      float64
Количество покупок                                         int64
Количество покупок.1                                     float64
Количество покупок на платящего пользователя             float64
Выручка, RUB                                             float64
Средняя выручка на пользователя, RUB                     float64
Средняя выручка на платящего пользователя, RUB           float64
Вернувшиеся                                                int64
Выручка, RUB.1                                           float64
CR воронки покупок, %                                      int64
Ошибки                                                     int64
CSI                                                        int64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 17 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Дата                                            125 non-null    datetime64[ns]
 1   Пользователи                                    125 non-null    int64
 2   Новые пользователи                              125 non-null    int64
 3   Доля новых пользователей                        125 non-null    float64
 4   Количество платящих пользователей               125 non-null    int64
 5   Количество платящих пользователей.1             125 non-null    float64
 6   Количество покупок                              125 non-null    int64
 7   Количество покупок.1                            125 non-null    float64
 8   Количество покупок на платящего пользователя    125 non-null    float64
 9   Выручка, RUB                                    125 non-null    float64
 10  Средняя выручка на пользователя, RUB            125 non-null    float64
 11  Средняя выручка на платящего пользователя, RUB  125 non-null    float64
 12  Вернувшиеся                                     125 non-null    int64
 13  Выручка, RUB.1                                  125 non-null    float64
 14  CR воронки покупок, %                           125 non-null    int64
 15  Ошибки                                          125 non-null    int64
 16  CSI                                             125 non-null    int64
dtypes: datetime64[ns](1), float64(8), int64(8)
memory usage: 16.7 KB

In [7]:
df.head()

,Дата,Пользователи,Новые пользователи,Доля новых пользователей,Количество платящих пользователей,Количество платящих пользователей.1,Количество покупок,Количество покупок.1,Количество покупок на платящего пользователя,"Выручка, RUB","Средняя выручка на пользователя, RUB","Средняя выручка на платящего пользователя, RUB",Вернувшиеся,"Выручка, RUB.1","CR воронки покупок, %",Ошибки,CSI
0,2017-12-31,23095,1603,0.069409,1828,0.009687,2309,0.005166,1.263129,0.006339,137.544230,1737.737418,21492,3.176584e+06,19,18854,82
1,2017-12-30,29918,2116,0.070727,2727,0.014452,3413,0.007637,1.251558,0.007972,133.536032,1465.027869,27802,3.995131e+06,19,17506,88
2,2017-12-29,38953,3029,0.077760,4219,0.022358,5142,0.011505,1.218772,0.013854,178.231792,1645.570751,35924,6.942663e+06,18,10910,88
3,2017-12-28,41326,3228,0.078111,4710,0.024960,5732,0.012826,1.216985,0.015377,186.466825,1636.078131,38098,7.705928e+06,17,17235,85
4,2017-12-27,34148,2199,0.064396,3018,0.015994,3713,0.008308,1.230285,0.009173,134.607649,1523.055666,31949,4.596582e+06,13,14190,88

In [10]:
df.corr().loc[['Выручка, RUB.1']]

,Пользователи,Новые пользователи,Доля новых пользователей,Количество платящих пользователей,Количество платящих пользователей.1,Количество покупок,Количество покупок.1,Количество покупок на платящего пользователя,"Выручка, RUB","Средняя выручка на пользователя, RUB","Средняя выручка на платящего пользователя, RUB",Вернувшиеся,"Выручка, RUB.1","CR воронки покупок, %",Ошибки,CSI
"Выручка, RUB.1",0.838978,0.843391,0.237746,0.935762,0.935762,0.942241,0.942241,0.423344,1.0,0.966441,0.801188,0.806211,1.0,0.482969,-0.016976,0.023463

In [15]:
df_corr = df.corr().loc[['Выручка, RUB.1']].T
df_corr[df_corr['Выручка, RUB.1'] > 0.7]

                                                Выручка, RUB.1
Пользователи                                          0.838978
Новые пользователи                                    0.843391
Количество платящих пользователей                     0.935762
Количество платящих пользователей.1                   0.935762
Количество покупок                                    0.942241
Количество покупок.1                                  0.942241
Выручка, RUB                                          1.000000
Средняя выручка на пользователя, RUB                  0.966441
Средняя выручка на платящего пользователя, RUB        0.801188
Вернувшиеся                                           0.806211
Выручка, RUB.1                                        1.000000