Для сайта, продающего билеты в кино, составлен список метрик. Определите наиболее
значимые из них.

In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_excel('Dataset-2.xlsx'
                   , sheet_name='Лист2'
                   , usecols=range(9)
                   , names=['date', 'revenue', 'yield_percent', 'mau', 'new', 'ressurected', 'cnt_items', 'errors', 'avg_check'])
df.head()

,date,revenue,yield_percent,mau,new,ressurected,cnt_items,errors,avg_check
0,02.сент,600000.0,91,6209971.0,1271736,4938235.0,1218.323587,3715,492.480000
1,03.сент,539800.0,98,6138791.0,1447192,4691599.0,1747.030049,3200,308.981520
2,05.сент,809765.0,92,6392179.0,1195080,5197099.0,2017.756255,2915,401.319534
3,06.сент,978651.0,100,7697321.0,1387697,6309624.0,2240.143369,1550,436.869806
4,07.сент,769542.0,97,6698070.0,1752918,4945152.0,1578.282828,1501,487.581811

In [18]:
df.corr().iloc[:1, 1:]

,yield_percent,mau,new,ressurected,cnt_items,errors,avg_check
revenue,0.703224,0.884078,-0.069135,0.854884,0.342768,-0.34811,0.656413

In [16]:
df.corr().style.background_gradient(cmap='RdYlGn')